- .env
- .eslintrc.json
- .github/workflows/build_and_push.yml
- src/app/App.tsx
- adds a default `PUBLIC_URL` to `.env`
- sidenote: this could be randomized during tests to help prevent accidental hard-coding of paths. @dakotablair thoughts?
- add `PUBLIC_URL` as the `react-router` `basename`, to ensure links work correctly
- add appropriate env variable values to the build action
> URO-29 Added env variable support/defaults for PUBLIC_URL and REACT_APP_AUTH_SERIVCE_URL

- .stylelintrc.json
- scripts/lint.fix.sh
- scripts/lint.sh
- scripts/lint.strict.sh
- src/app/App.module.scss
- src/common/colors.scss
- src/features/layout/LeftNavBar.module.scss
- src/features/layout/TopBar.module.scss
- src/stories/styles/color-examples.scss
- src/stories/styles/colors.stories.mdx
This PR fixes the stylelint scripts to correctly lint all scss files. Some configuration is added to grandfather in current practice, but this can be revisited in a later configuration change. The biggest conceptual change is that `use_color` and `use_rgba_color` are now named `use-color` and `use-rgba-color` respectively.
> Fix stylelint and align scss to standard.

- .github/workflows/build_and_push.yml
Updating to call CI for auth instead of next-dev, now that the content is running in CI.
> Updating  REACT_APP_AUTH_SERIVCE_URL

- .eslintignore
The `lint:strict` script was behaving poorly because it was attempting to lint the coverage artifacts which it should not do.
> URO-80: Add coverage directory to eslintigorne.

- .eslintrc.json
Prettier will manage line length, and enabling the eslint `max-len` rule will cause conflicting messages in certain situations.
> Remove redundant line length rule.

- .github/workflows/build_and_push.yml
(this will break the app if accessed directly via the ci service url, which is ok)
> Fix internal links on ci-europa

- package-lock.json
- package.json
- src/app/App.test.tsx
- src/app/App.tsx
- src/app/Routes.tsx
- src/app/store.ts
- src/common/types.ts
- src/features/auth/authSlice.ts
- src/features/layout/TopBar.tsx
- src/features/profile/Profile.module.scss
- src/features/profile/Profile.test.tsx
- src/features/profile/Profile.tsx
- src/features/profile/common.ts
- src/features/profile/profileSlice.test.ts
- src/features/profile/profileSlice.ts
- src/stories/components/Profile.stories.tsx
- tsconfig.json
URO-52 Profile component: This commit introduces <ProfileWrapper /> to manage state of profile view. The <Profile /> component is mostly a template and holds very little logic, but handles passing the profile data to the profile view and
the narrative view.
URO-65 Profile slice: The new profile slice holds all data which is visible in the profile view. This commit introduces an ad-hoc caching layer for profile data. It retrieves data from the profile service using @kbase/narrative-utils.
This commit also includes the Meta type to avoid explicitly typing portions of service call responses not currently implemented. It factors <Routes /> into its own module and adds jest-fetch-mock for testing HTTP requests.
> URO-52, URO-65 Add profile slice and component.

- package-lock.json
- package.json
- src/app/Routes.tsx
- src/features/layout/PageNotFound.tsx
- src/features/layout/TopBar.tsx
- src/features/legacy/Legacy.tsx
This PR updates usage of React Router to v6. I mostly followed the [instructions in the official guide](https://github.com/remix-run/react-router/discussions/8753), but the project is small enough at this point that I skipped using the `react-router-dom-v5-compat` package.
Please double check [this line](https://github.com/kbase/ui-refresh-test/pull/48/files#diff-b7d533292606d4bca64b9e33f402524c5cf5e62d893fb457d9ff8f65843756daL19-R20) and make sure it is still doing what is expected.
This PR is built on top of #46 but it can be interchanged if necessary. [Here is the diff](https://github.com/kbase/ui-refresh-test/compare/rtk_query_api...react-router-v6) of changes from that PR's branch
> React router v6

- src/common/components/PlaceholderFactory.tsx
This PR relaxes the conditions under which Placeholder components are prohibited. In particular, allow them in the `ci-europa` environment.
> URO-146 Allow placeholder components in test environments.

- src/common/api/searchApi.ts
- src/common/api/workspaceApi.ts
- src/common/types/NarrativeDoc.tsx
- src/features/navigator/NarrativeList/NarrativeList.fixture.tsx
- src/features/navigator/NarrativeList/NarrativeList.tsx
- src/features/navigator/NarrativeList/NarrativeViewItem.test.tsx
- src/features/navigator/NarrativeList/NarrativeViewItem.tsx
- src/features/navigator/NarrativeView.fixture.tsx
- src/features/navigator/NarrativeView.test.tsx
- src/features/navigator/NarrativeView.tsx
- src/features/navigator/Navigator.test.tsx
- src/features/navigator/Navigator.tsx
- src/features/navigator/hooks.ts
- src/features/navigator/navigatorSlice.ts
> URO-149 Connect data and preview views to API

- src/common/api/collectionsApi.ts
- src/features/collections/data_products/TaxaCount.module.scss
- src/features/collections/data_products/TaxaCount.tsx
Relatively trivial, mostly just duplicating code from the match bar.
> RE2022-125 Add selected bar type to taxacount chart

- src/common/api/collectionsApi.ts
- src/common/api/searchApi.ts
- src/features/collections/CollectionDetail.tsx
- src/features/collections/ExportPane.tsx
- src/features/collections/MatchPane.tsx
- src/features/collections/SelectionPane.tsx
- src/features/collections/collectionsSlice.ts
- src/features/collections/data_products/GenomeAttribs.tsx
- src/features/collections/data_products/TaxaCount.tsx
- src/features/collections/hooks.ts
- [Add basic export pane, api endpoints](https://github.com/kbase/ui-refresh-test/pull/77/commits/2c0417b657e3644827d9b60ba7332e1b46adb24b)
- [Use new+better narrative select in matching pane](https://github.com/kbase/ui-refresh-test/pull/77/commits/959e45a05109b44928cb4c505de6edc339eed690)
- with the help of @dakotablair narrative selects are now way more usable
- [Display links to export results, and show export errors](https://github.com/kbase/ui-refresh-test/pull/77/commits/64504848912fcb68bc2e028c0c4d8f4a4955ab29)
- [Refactor selection to only create server selection when useSelectionI…](https://github.com/kbase/ui-refresh-test/pull/77/commits/468b6e6470fe73c21469255a9933e32bd8120d6e)
- as noted by @MrCreosote, creating a selection for every change is overkill. This commit adds a …
> RE2022-166 RE2022-167 Export

- src/common/api/collectionsApi.ts
- src/features/collections/CollectionDetail.tsx
- src/features/collections/hooks.ts
Merging into `microtrait-all` (should I use `feature/microtrait`?) so I can keep microtrait things isolated from `main` for now. Also allows for a final review of `microtrait-all` before merging if we want.
see https://kbase-jira.atlassian.net/browse/RE2022-173 for ACs etc.
>   RE2022-173 Add microtrait API methods and useMicrotrait table hook stub

- README.md
- package-lock.json
- package.json
The previous version of node-sass (6.0.1) was causing issues with a clean install of the repo. It's been upgraded to the latest version.
I also added a section to the README to help with troubleshooting node version issues and host check issues during the install process.
> Fix issues with node-sass and install process

- src/common/api/workspaceApi.ts
- src/features/navigator/NarrativeControl/Share.tsx
- src/features/navigator/common.ts
- src/features/navigator/navigatorSlice.ts
This PR adds the API calls for updating sharing in the narrative control menu. This is also the final piece of functionality for the Navigator as a whole. That is, no major new functionality remains for Navigator itself. In particular, the narrative navigator is now feature complete.
> URO-82, URO-168 Add share narrative function.

- src/features/navigator/common.ts
Previously, outgoing narrative links always went to the CI environment.
> Update narrative links to be environment aware.

- src/app/Routes.tsx
- src/features/legacy/Fallback.tsx
This fixes the double-chrome (iframe nesting) issue caused by our new nginx redirect for legacy 404s
> add europa fallback page for legacy 404s

- src/common/components/LabelValueTable.module.scss
- src/features/navigator/NarrativeList/NarrativeList.module.scss
- src/features/navigator/NarrativeList/NarrativeViewItem.tsx
- src/features/navigator/NarrativeMetadata.tsx
- src/features/navigator/Navigator.module.scss
Some smalls UI changes to the navigator UI as mentioned in my comments in the navigator feedback doc:
- Add padding to narrative metadata
- Improves readability and aesthetic of the metadata tables
- Add space to the left of narrative actions menu
- These two elements were right up against each other. This is just a small visual improvement.
- Fix narrative title alignment and icon position
- This fixes a slight misalignment with the narrative title and the icons in that component
- This also moves the new-window icon to the right of the title. It's more common to see this icon at the end of a link and it helps improve the readability of the link content.
- Fix author name overflow and add better responsiveness to metadata columns
- This fixes an issue with some metadata columns …
> Navigator UI Tweaks

- src/features/legacy/Legacy.tsx
> URO-145: Use more secure message targets, implement europa.identify postMessage

- .env
- Dockerfile
- config.json
- scripts/build_deploy.sh
- src/app/App.tsx
- src/app/Routes.tsx
- src/app/store.ts
- src/common/components/Dropdown.module.scss
- src/common/components/Select.tsx
- src/features/layout/TopBar.module.scss
- src/features/layout/TopBar.tsx
- src/features/layout/layoutSlice.ts
- src/features/legacy/Legacy.test.tsx
- src/features/legacy/Legacy.tsx
- src/features/navigator/NarrativeControl/NarrativeControl.module.scss
> URO-28, URO-126, URO-127, URO-142: Fixed logout, authed collections, aligned topbar, created canonical build configuration file.

- src/app/App.tsx
- src/features/layout/TopBar.tsx
- src/features/legacy/Legacy.tsx
> Fix topbar logout hang and unknown env

- public/index.html
- src/app/Routes.tsx
- src/common/hooks.ts
- src/features/navigator/Navigator.test.tsx
- src/features/profile/Profile.test.tsx
> URO 95: Configure Google Analytics 4

- config.json
- src/features/layout/TopBar.tsx
- src/features/layout/layoutSlice.ts
After exhaustive troubleshooting, I found the root cause behind the `404` errors on the `next` cluster:
``The next environment wasn't defined in Europa's env configs!``
I've updated the relevant files to include, and thus build code for, a `next` env, which now shows up under `/deploy/next`.
I've gone ahead and tested this in the next cluster using image ``ghcr.io/kbase/ui:br-DEVOPS-1412-next``.
> DEVOPSs1412 :  Europa on Next

- src/common/components/Sidebar.module.scss
- src/common/components/Table.module.scss
- src/common/components/Table.tsx
- src/common/utils/stringUtils.ts
- src/features/collections/CollectionDetail.tsx
- src/features/collections/Collections.module.scss
- src/features/collections/CollectionsList.tsx
- src/features/collections/data_products/Biolog.tsx
- src/features/collections/data_products/GenomeAttribs.tsx
- src/features/collections/data_products/Microtrait.tsx
- src/features/collections/data_products/SampleAttribs.tsx
- src/features/collections/data_products/TaxaCount.module.scss
- src/features/collections/data_products/TaxaCount.tsx
- Moves Collection filter menu into a panel in the main content area
- Makes filter panel expand to fill height of window and lets users scroll to see additional filters
- Right side of content area is pushed to the right when panel is open
- Elements in data products have consistent panels wrapped around them
- Adds padding around pagination components and table toolbars
- Adds row count text above tables and heatmaps
> Update Collection filter panel layout

- config.json
- src/features/layout/TopBar.tsx
- src/features/layout/layoutSlice.ts
Adding section for the `narrative2` environment for testing in a more production-like environment.
>  add narr2 enviroment

- src/common/api/collectionsApi.ts
- src/common/colors.scss
- src/common/components/Sidebar.module.scss
- src/common/components/Sidebar.tsx
- src/common/components/Table.module.scss
- src/common/components/Table.test.tsx
- src/common/components/Table.tsx
- src/features/collections/CollectionDetail.tsx
- src/features/collections/CollectionSidebar.tsx
- src/features/collections/collectionsSlice.ts
- src/features/collections/data_products/GenomeAttribs.tsx
- src/features/collections/data_products/SampleAttribs.tsx
Update the style of the table headers and use the display name for their text instead of the field name. Also use the column type to change the alignment for number columns.
Also includes some style changes to the sidebar.
> Update table UI

- src/common/cookie.ts
- src/features/auth/authSlice.test.tsx
- src/features/auth/hooks.ts
1. Before this bugfix, Europa did its best to isolate its own TLD cookie from legacy.* domains. However, this was causing a mismatch in the auth state between Europa and Legacy.
2. Cookie expiration in Europa was running AFTER cookie checks in legacy
3. Legacy flow fails for Google if an invalid cookie is present AT ALL during the login/continue flow endpoint, but it wasn't deleted before the flow, as Europa-cookie-clearing was losing the race condition when the intermediate login page (account choice) wasn't present. It was also losing the race condition on the login page itself and redirecting there when cookies were invalid (meaning cookies were never being deleted)
4. Europa no longer "hesitates" to delete bad cookies until after legacy load (resolving the race condition), and makes …
> PUBLIC-2722 Fix Google Re-login bug

- src/features/collections/CollectionDetail.tsx
- src/features/common.ts
Fixes three items from the bug punchlist:
- closest_placement_af and possibly other sliders show errors after sliding and cannot be recovered
- fixed by setting `step`
- Filter slider handle does not move until have mouse-up
- fixed by isolating slider state from form/filter state
- Removing filter doesn’t reset the filter UI
- fixed by adding an effect to filter controls
> Fix slider debouncing, fix slider steps, fix slider clear

- src/features/collections/CollectionDetail.tsx
- src/features/collections/CollectionOverview.tsx
- src/features/collections/data_products/SampleAttribs.tsx
- src/features/collections/data_products/TaxaCount.tsx
Fix taxa chart menu overflow. Make species the default option in taxa chart. Adjust panel spacing.
> Bugfixes to overview page.

- src/features/collections/CollectionDetail.tsx
- src/features/collections/data_products/SampleAttribs.tsx
Button colors had an issue where they were too light to read. This is fixed.
Also, removes checkboxes from the samples table because they can't be selected right now.
> Fix button colors and sample table

- src/common/api/collectionsApi.ts
- src/common/api/workspaceApi.ts
- src/common/components/Input.tsx
- src/features/collections/ExportModal.tsx
- src/features/collections/SelectionModal.tsx
- src/features/navigator/NarrativeControl/Share.tsx
fixes three punchlist bugs:
- `Don’t show read-only narratives in the export select box`
- `Export form needs improved error states`
- `In export GUI, Data Object Name -> New [Genome | Assembly] Set Object Name`
also fixes input blur/focus handler forwarding and disables the export button in the select modal when there is no selection.
> Fix Export Form

- src/app/Routes.tsx
- src/features/layout/TopBar.tsx
- src/features/layout/layoutSlice.ts
- Pulls login menu disabled state into redux, and creates a wrapper element for use in Routes.tsx which controls said state.
- Use MUI `Button` with 'link' role in place of existing react-router `Link` (this slightly changes the text style on the button, but I think this is ok, may be worth a check with @codytodonnell)
> URO-189 (suggestions) add DisabledLogin wrapper element, state.layout.loginControlDisabled

- src/common/components/DataView.tsx
- src/common/components/index.tsx
- src/features/collections/ExportModal.tsx
- src/features/collections/data_products/Biolog.tsx
- src/features/collections/data_products/HeatMap.module.scss
- src/features/collections/data_products/HeatMap.tsx
- src/features/collections/data_products/Microtrait.tsx
This PR adds dataview links to heatmap tooltips. It also abbreviates row and column names in the heatmap. The full names are included in the tooltip. These abbreviations are not always unique, and plotly performs poorly in that case, so a zero-width workaround is included to fix this issue.
> Refine and fix bugs in heatmap data products.

- src/features/layout/LeftNavBar.tsx
Enable collections for everyone. The `UI_COLLECTIONS` custom role now has no meaning.
> Make Collections NavItem public

- public/index.html
Use a Google CDN to serve our web font so that it is easier to distinguish `l` from `I`.
> Add Oxygen Google Font headers

- src/common/components/Table.module.scss
- src/common/components/Table.tsx
- src/features/collections/CollectionDetail.tsx
- src/features/collections/CollectionOverview.tsx
- src/features/collections/Collections.module.scss
- src/features/collections/MatchModal.tsx
- src/features/collections/data_products/GenomeAttribs.tsx
- src/features/collections/data_products/SampleAttribs.tsx
- src/features/collections/data_products/TaxaCount.module.scss
**New Context Tab Layout**
This moves the context tabs into the top detail header and the filters down into the main data product content area. The goal is to make it more clear that the filters applied can be different between the different tabs (All, Matched, Selected).
**Other UI Modifications**
- Pagination re-styled and duplicated on top and bottom of tables
- Match button color change
- Changed matched bar color in taxa chart to match button and row highlight
> Switch context tabs and filters positions in layout hierarchy

- src/common/api/collectionsApi.ts
- src/features/collections/CollectionDetail.tsx
- src/features/collections/data_products/TaxaCount.tsx
> Taxa Count bugfixes

- src/common/utils/stringUtils.ts
- src/features/collections/CollectionDetail.tsx
Sliders will now use the greatest number of decimal places in their max or min value to determine the step. For example, if the min is 3.125 and the max is 10.5, the step would be 0.001.
> Fix slider step precision

- src/features/collections/CollectionDetail.tsx
Fixes slider NaN bug by validating inputs before updating slider enables inclusive ranges (can now specify a range with equal min&max)
> Fix Filter Slider NaN Bug

- src/common/components/Table.module.scss
- src/common/components/Table.tsx
Fixes bug causing table loader overlay not to expand over the scrollable parts of the table. The table overlay now expands across all the columns, but the loader icon is still only visible on the far left of the table. To make sure users still know that the table is loading when scrolled to the right, I added a background animation.
> Expand table loader overlay and add bg animation

- src/common/api/collectionsApi.ts
- src/common/hooks.ts
- src/features/collections/MatchModal.tsx
- src/features/collections/collectionsSlice.ts
- src/features/collections/data_products/Biolog.tsx
- src/features/collections/data_products/Microtrait.tsx
- src/features/collections/data_products/SampleAttribs.tsx
- src/features/collections/data_products/TaxaCount.tsx
- src/features/collections/hooks.ts
adds a new helper for polling based on proccessState fields and fixes the following bug
> Match count bugfix and process state backoff polling helper

- src/features/collections/data_products/Biolog.tsx
- src/features/collections/data_products/Microtrait.tsx
- src/features/collections/hooks.ts
> RE2022-236 Heatmap context tabs

- src/common/components/Button.module.scss
- src/features/collections/data_products/Biolog.tsx
- src/features/collections/data_products/HeatMap.module.scss
- src/features/collections/data_products/Microtrait.tsx
Tooltips to show when hovering over a cell in the heatmaps. Tooltip design could be reused in other areas of the app.
> RE2022-254: Modify heatmap tooltips

- src/common/api/collectionsApi.ts
- src/common/components/FilterChip.tsx
- src/features/collections/CollectionDetail.tsx
- src/features/collections/Filters.tsx
- src/features/collections/collectionsSlice.ts
- src/features/collections/data_products/Biolog.tsx
- src/features/collections/data_products/Microtrait.tsx
This PR also adds support for the "Bool" type filter, but implements it as a range filter (as that's all we have UI for at the moment).
> RE2022-310 Implement Heatmap filters

- README.md
- docs/adrs/0000-ADR-template.md
- docs/adrs/0001-CRA-and-general-architecture.md
- docs/adrs/0003-forms.md
- docs/adrs/0005-tables.md
- docs/adrs/0006-Component-Library.md
- src/features/collections/README.md
> Add status badge, polish documentation.

- src/common/api/index.ts
- src/features/icons/AppCellIcon.test.tsx
- src/features/profile/profileSlice.test.tsx
- src/test/data/narrative_method_store.ts
- src/test/data/user_profile.ts
- src/test/jsonrpc11.ts
- src/test/kbaseServiceMock.ts
- src/test/settings.ts
This PR extracts changes form the rest of URO-211, which adds support for creating ORCID Links (but deleting, managing, or user profile integration). 
The tests for those changes requires extensive mocking of orcidlink service endpoints. It was then that I discovered that the baseUrl was not specifically configured for the test environment. Rather, without this configuration it defaulted to the production urls - which in turn default to CI. Two sets of tests were actively contacting CI services in their tests and immediately broken when I added support for the test environment baseUrl to orient to http://localhost.
So this set of changes includes:
- setting baseUrl to http://localhost for the node test enviromnet
- improving support for KBase JSON-RPC 1.1 service mocking
- updating two …
> URO-211 part A - support for kbase service mocking

- src/common/components/Table.tsx
- src/features/collections/README.md
- src/features/collections/data_products/GenomeAttribs.tsx
adds default hidden/visible columns, frees Gavin from UI meetings
To compare this and the previous state of things, see the default hidden columns / selected in the dropdown at https://ci-europa.kbase.us/collections/GTDB/genome_attribs vs localhost (fewer visible by default)
> Support Default Columns (last PR for v1.0.10)

- scripts/build_deploy.ts
- src/features/auth/authSlice.test.tsx
- src/features/auth/hooks.ts
This PR fixes the backup cookie issue. It fixes the cookie configuration, adds tests specific to the backup cookie, and adds a missing condition that obfuscated the configuration error and accidentally worked only on login/logout or when a backup cookie was already present.
> Fix Backup cookie

- src/features/auth/hooks.ts
Super minor PR to remove a call that always fails (auth/me before we have loaded the login token)
> Fix initial auth/me call, skip query until token is defined

- src/test/mockRTKQuery.ts
- src/test/mockRTKQueryMeta.test.tsx
- Add mockQuery utility for query endpoints
- Add mockMutation utility for mutations
- Add tests for these mocks
- Support loading, error, and success states
> Add test utilities for mocking RTK Query hooks in unit tests
