kbase/ui

.github/workflows/build_and_push.yml
=> `/services/static` -> `/services/static-content`

package-lock.json, package.json, src/common/components/Dropdown.module.scss, src/common/components/Dropdown.tsx, src/common/components/Select.module.scss, src/common/components/Select.tsx, src/common/components/index.ts, src/features/layout/TopBar.module.scss, src/features/layout/TopBar.tsx
- ~~**Does not have functional menu items, they are just stubbed** this is due to not currently having access to external services. This either should be merged once we determine the appropriate behavior for each item, or we should generate a new JIRA task for filling these out. (This would also likely be the right time to add tests)~~
- storybook stories for dropdown and select
You might notice the `:global(.react-select__[name])` entries in the scss files. These are for react-select style overrides. If this is too arcane, we could also do this in JS using a different API they provide (which is less... weird). However, if we do a lot of customization of this component, it is probably best to have it in an .scss file. It's sort of a tradeoff...
For both select and dropdown, I forwarded …
=> URO-32 URO-34 TopBar Dropdown Menu

docs/adrs/003-forms.md
[docs/adrs/003-forms.md](https://github.com/kbase/ui-refresh-test/pull/18/files#diff-238fc1f47859266824e752307b91df655d1be3051e88bdb4a94d6d87292772a8R1)
=> URO-42 Form State and Validation

src/app/App.tsx, src/features/legacy/Legacy.tsx
Things seems to be working quite well here. Unfortunately no storybook or tests for this one, as both are quite difficult to do given the self-referential iframe...
=> Add /legacy/* route and support

.env, package-lock.json, package.json, src/common/services.ts, src/features/auth/Auth.tsx, src/features/auth/authSlice.ts
This PR also adds the `ENV` environment variable which determines the KBase environment to use.
=> Add service client configuration.

.env
=> Change base URL

docs/adrs/0004-RTK-Query.md, src/common/api/authService.ts, src/common/api/htmlFileSetServApi.ts, src/common/api/narrativeMethodStore.ts, src/common/api/serviceWizardApi.ts, src/common/api/userProfileApi.ts, src/common/api/utils/kbService.ts, src/common/api/utils/kbaseBaseQuery.ts, src/common/api/utils/serviceHelpers.ts, src/common/api/wsObjectApi.ts, src/common/utils/stringUtils.test.ts, src/common/utils/stringUtils.ts
supporting PR for collections, also cleans up and provides better error handling (actually expose server errors) for auth
=> Add http/rest api support and uriEncodeTemplateTag util

.github/workflows/build_and_push.yml, .github/workflows/pull-request.yml
Build now runs during PR checks, see the checks for this PR
=> URO-131 Add Build step to PR Workflow

src/common/api/searchApi.ts, src/common/api/utils/kbaseBaseQuery.ts, src/common/api/utils/parseError.test.ts, src/common/hooks.ts, src/features/common.ts, src/features/navigator/NarrativeList/NarrativeList.fixture.tsx, src/features/navigator/NarrativeList/NarrativeViewItem.tsx, src/features/navigator/Navigator.test.tsx, src/features/navigator/Navigator.tsx, src/features/navigator/RefreshButton.test.tsx, src/features/navigator/RefreshButton.tsx, src/features/navigator/hooks.ts, src/features/navigator/navigatorSlice.ts, src/features/params/paramsSlice.ts, src/features/profile/Profile.test.tsx
[URO-82]: https://kbase-jira.atlassian.net/browse/URO-82
[URO-143]: https://kbase-jira.atlassian.net/browse/URO-143
=> URO-82 URO-143 Connect search

src/common/api/collectionsApi.ts, src/common/components/Table.tsx, src/features/collections/MatchPane.tsx, src/features/collections/data_products/GenomeAttribs.tsx, src/features/collections/data_products/TaxaCount.tsx
- [Fix TaxaCount loading issues](https://github.com/kbase/ui-refresh-test/pull/68/commits/12e19b31418e4e21c7666ff14156adcc515d48fe)
[12e19b3](https://github.com/kbase/ui-refresh-test/pull/68/commits/12e19b31418e4e21c7666ff14156adcc515d48fe)
- [Add maxPage to table, fix table count](https://github.com/kbase/ui-refresh-test/pull/68/commits/324c668aaffe6ca4e4c6dcdb9f68d35424cf7ac8)
[324c668](https://github.com/kbase/ui-refresh-test/pull/68/commits/324c668aaffe6ca4e4c6dcdb9f68d35424cf7ac8)
- [support set types](https://github.com/kbase/ui-refresh-test/pull/68/commits/b3880ba681d87d84a0186136d2f84a655cf47e00)
[b3880ba](https://github.com/kbase/ui-refresh-test/pull/68/commits/b3880ba681d87d84a0186136d2f84a655cf47e00)
=> RE2022-128 RE2022-129 Matching fixes

src/app/store.ts, src/common/api/collectionsApi.ts, src/features/collections/CollectionDetail.tsx, src/features/collections/MatchPane.tsx, src/features/collections/SelectionPane.tsx, src/features/collections/collectionsSlice.ts, src/features/collections/data_products/GenomeAttribs.tsx
does not include any selection UI within data products
=> RE2022-122 Add selection pane, api calls, and basic state management

src/common/api/collectionsApi.ts, src/common/components/CheckBox.tsx, src/common/components/Table.test.tsx, src/common/components/Table.tsx, src/features/collections/Collections.module.scss, src/features/collections/MatchPane.tsx, src/features/collections/SelectionPane.tsx, src/features/collections/data_products/GenomeAttribs.module.scss, src/features/collections/data_products/GenomeAttribs.tsx, src/features/collections/data_products/TaxaCount.tsx, src/stories/components/Table.stories.tsx
Apologies for another ginormous PR... I recommend reviewing the Table code commit-wise as there are a good amount changes due to the refactor. However, we already went over some of that I think, _and_ I have 100% test cov on Table, so tests could be a good place to start too.
- Adds selection to Genome Attribs
- adds helper buttons for (de)selecting matches
- adds checkboxes
- Table refactor for ease of use, better tests
- maintains 100% Test cov on Table :)
=> RE2022-121 RE2022-124 Genome Attrib Selection UI and Related Table Refactor

package-lock.json, package.json, src/common/api/collectionsApi.ts, src/common/components/Select.test.tsx, src/common/components/Select.tsx, src/features/collections/MatchPane.tsx, src/features/collections/MatcherUserParams.tsx
- @dakotablair we may want to discuss JSONSchema Libs. Here I added `ajv` as a proof of concept.  There are some (3 up-to-date, really) options though: https://json-schema.org/implementations.html#validator-javascript
=> RE2022-154 Adds Rank Parameter support to collections matching UI

src/common/components/Table.tsx, src/features/collections/data_products/GenomeAttribs.tsx
So that it may be shared with the heatmap and/or not included when a table is rendered
- Need to add tests still
=> Minor Refactor: Extract pagination component from Table

src/common/api/collectionsApi.ts, src/features/collections/data_products/Microtrait.tsx, src/features/collections/data_products/TaxaCount.tsx
to align to these API changes: https://github.com/kbase/collections/pull/342/commits/e4d44885d4a86dbbff30e1f81eeedfac112ab84e
=> update selection/match state key names

src/common/api/collectionsApi.ts, src/common/components/Table.tsx, src/features/collections/DataProduct.tsx, src/features/collections/data_products/SampleAttribs.tsx
Adds a simple table for samples flattened by kbase_id. Implements matching and selection.
Other small changes
- Hide the max pagination button when it is greater than the max viewable page
=> RE2022-216 Add Sample Attributes DataProduct

src/common/colors.scss, src/common/components/Button.module.scss, src/common/components/Button.tsx, src/common/components/Input.module.scss, src/common/components/Input.tsx, src/common/components/LabelValueTable.module.scss, src/common/components/LabelValueTable.tsx, src/common/components/LinkButton.tsx, src/common/components/Select.module.scss, src/features/navigator/NarrativeList/NarrativeList.module.scss, src/features/navigator/NarrativeList/NarrativeViewItem.tsx, src/features/navigator/NarrativeMetadata.tsx, src/features/navigator/NarrativeView.tsx, src/features/navigator/Navigator.module.scss, src/features/navigator/Navigator.tsx, src/features/navigator/RefreshButton.tsx, src/features/navigator/SearchInput.tsx
Includes changes to the Navigator layout and styles as well as some global changes to components that are used in the Navigator components (e.g. Button, Input).
Added a new component LabelValueTable to display the metadata section in the narrative view. This still needs a section in storybook.
=> Update Navigator styles

src/app/App.tsx, src/common/components/Button.module.scss, src/common/components/Button.tsx, src/common/components/Table.module.scss, src/common/components/Table.tsx, src/features/collections/CollectionDetail.tsx, src/features/collections/Collections.module.scss, src/features/collections/CollectionsList.tsx, src/features/collections/DataProduct.tsx, src/features/collections/ExportModal.tsx, src/features/collections/MatchModal.tsx, src/features/collections/MatchPane.tsx, src/features/collections/MatcherUserParams.tsx, src/features/collections/SelectionModal.tsx, src/features/collections/data_products/GenomeAttribs.tsx, src/features/collections/data_products/SampleAttribs.tsx, src/features/layout/Modal.module.scss, src/features/layout/Modal.tsx, src/features/layout/layoutSlice.ts
See https://kbase-jira.atlassian.net/browse/RE2022-225
Also fixes https://kbase-jira.atlassian.net/browse/RE2022-200
=> RE2022-225 RE2022-200 Phase 0 Collections Detail page (and everything else)

src/app/App.tsx, src/common/components/Loader.tsx, src/common/components/Table.tsx, src/features/auth/Auth.tsx, src/features/collections/CollectionDetail.tsx, src/features/collections/MatchModal.tsx, src/features/collections/data_products/HeatMap.tsx, src/features/collections/data_products/TaxaCount.tsx, src/features/navigator/NarrativeView.tsx, src/features/profile/Profile.tsx
Adds a really simple loader component. This will need more presentation work in the future, but it will be nice to have a common component for this.
=> Add simple/placeholder Loader component

src/common/components/Input.tsx, src/features/layout/LeftNavBar.tsx
I probably should have tacked this on to PR #107.
=> Fix DevNav hostname logic, input maxLength prop.

src/common/colors.scss, src/common/components/LabelValueTable.module.scss, src/common/components/LabelValueTable.tsx, src/features/navigator/NarrativeControl/NarrativeControl.module.scss, src/features/navigator/NarrativeControl/index.tsx, src/features/navigator/NarrativeList/NarrativeList.module.scss, src/features/navigator/NarrativeList/NarrativeList.tsx, src/features/navigator/NarrativeList/NarrativeViewItem.tsx, src/features/navigator/NarrativeMetadata.tsx, src/features/navigator/NarrativeView.tsx, src/features/navigator/Navigator.module.scss, src/index.scss
=> URO-153, URO-154: Presentation for Narrative View Selection and Control Menu

src/common/api/feedsService.ts, src/features/layout/LeftNavBar.module.scss, src/features/layout/LeftNavBar.tsx
=> URO-178: Add feeds notifcation count, feeds api

.env, Dockerfile, config.json, scripts/build_deploy.sh, src/app/App.tsx, src/app/Routes.tsx, src/app/store.ts, src/common/components/Dropdown.module.scss, src/common/components/Select.tsx, src/features/layout/TopBar.module.scss, src/features/layout/TopBar.tsx, src/features/layout/layoutSlice.ts, src/features/legacy/Legacy.test.tsx, src/features/legacy/Legacy.tsx, src/features/navigator/NarrativeControl/NarrativeControl.module.scss
This PR contains all code from PR #119, PR #121, and PR #122.
The image generated from this PR (`ghcr.io/kbase/ui:pr-123`) is meant to be deployed along with the following legacy `kbase-ui` image:
- [`ghcr.io/kbase/kbase-ui:pr1659`](http://ghcr.io/kbase/kbase-ui:pr1659)
This deployment configuration has been confirmed to be acceptable in the following environments:
=> Auxiliary Deployment PR

src/common/api/collectionsApi.ts, src/features/collections/ExportModal.tsx
Resolves https://kbase-jira.atlassian.net/browse/RE2022-273
Acceptance Criteria
=> RE2022-273 Add match_id to export to enable provenance

docs/adrs/0006-Component-Library.md, package-lock.json, package.json, src/common/api/collectionsApi.ts, src/common/components/Button.tsx, src/features/collections/CollectionDetail.tsx, src/features/collections/collectionsSlice.ts, src/features/collections/data_products/GenomeAttribs.tsx
I'm still not sure what the best way to use the material library is. This may require some discussion. For now, I am trying to keep the state separate in the base branch of this PR (in its own PR #129)
[RE2022-252]: https://kbase-jira.atlassian.net/browse/RE2022-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RE2022-251]: https://kbase-jira.atlassian.net/browse/RE2022-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RE2022-250 RE2022-253 Filtering: Basic material UI, updates genome attribs table

src/common/api/collectionsApi.ts, src/features/collections/data_products/Biolog.tsx, src/features/collections/data_products/GenomeAttribs.tsx, src/features/collections/data_products/Microtrait.tsx
Support still needed for samples, selections, see ticket comments
=> RE2022-286 Support displayname in genome attribs, biolog, microtrait

.env, config.json, scripts/build_deploy.sh, src/app/App.tsx, src/common/cookie.ts, src/features/auth/hooks.ts
Adds config and setter for backup tokens. I configured a mock backup token in the local dev environment in `.env`, too.
=> Add kbase_session_backup support

src/common/components/FilterChip.tsx, src/features/collections/CollectionDetail.tsx
Uses MUI tooltip (at least for now)
=> RE2022-251 Add filter chips

src/features/collections/SelectionModal.tsx, src/features/collections/collectionsSlice.ts, src/features/collections/data_products/Biolog.tsx, src/features/collections/data_products/GenomeAttribs.tsx, src/features/collections/data_products/Microtrait.tsx, src/features/collections/data_products/SampleAttribs.tsx
Fixes issue where selection would clear when opening the selection modal, and refactors `useSelectionId` to prevent extraneous calls to the server.
=> Refactor useSelectionId and fix selection modal clearing bug

src/common/components/Input.module.scss, src/common/components/Input.tsx, src/features/collections/Collections.module.scss, src/features/collections/ExportModal.tsx, src/features/collections/MatchModal.tsx, src/features/collections/MatcherUserParams.tsx, src/features/layout/Modal.module.scss
Fixes the layout of match and export modals. Also adds help text to the different matchers.
=> Clean match modals and export modal

src/common/components/Table.tsx, src/features/collections/data_products/GenomeAttribs.tsx
- Add cell rendering option to useTableColumns
- switch from html title to MUI tooltip
- align classification string rtl
- format number values using toLocaleString by default.
- Also adds FR from bug punchlist:
- > Ranjan FR: KBase IDs in Table should link to landing page
=> RE2022-317 Cell Rendering

src/common/components/Input.module.scss, src/common/components/Input.tsx, src/features/collections/CollectionDetail.tsx
Bugfixes
- Remove filter button from Samples (supports easily adding it back when we add filters to samples)
- Remove match button from Samples
=> Remove filter match buttons

src/features/collections/data_products/Biolog.tsx, src/features/collections/data_products/Microtrait.tsx
This PR fixes pagination in the Biolog and Microtrait data products.
=> Fix pagination continuation column name.

src/features/collections/CollectionDetail.tsx, src/features/collections/data_products/AttribHistogram.tsx, src/features/collections/data_products/AttribScatter.tsx, src/features/collections/data_products/GenomeAttribs.tsx, src/features/collections/data_products/SampleAttribs.tsx, src/features/collections/hooks.ts
- Adds sample filters
- shows sample name first
- adds sample link
- fixes genome link
- fixes sample table count text
=> RE2022-306 Sample Filters

src/features/collections/data_products/Biolog.tsx, src/features/collections/data_products/HeatMap.tsx
=> RE2022-236: Heatmap label fixes.

src/app/Routes.tsx
See [2f06f3](https://github.com/kbase/ui/commit/2f06f3).
My bad 😅
=> URO-185: Restored status view inadvertently removed.

src/common/hooks.ts, src/features/collections/ExportModal.tsx, src/features/collections/data_products/Biolog.tsx, src/features/collections/data_products/GenomeAttribs.tsx, src/features/collections/data_products/SampleAttribs.tsx, src/features/collections/hooks.ts
Solves RE2022-338 and other small state issues discovered in the process.
=> RE2022-338 Fix polling issues

src/app/Routes.tsx, src/common/api/authService.ts, src/common/components/Loader.tsx, src/common/index.ts, src/features/account/Account.module.scss, src/features/account/Account.test.tsx, src/features/account/Account.tsx, src/features/account/AccountInfo.test.tsx, src/features/account/AccountInfo.tsx, src/features/account/LinkedProviders.test.tsx, src/features/account/LinkedProviders.tsx, src/features/account/LogInSessions.test.tsx, src/features/account/LogInSessions.tsx, src/features/account/UseAgreements.tsx, src/features/auth/providers.module.scss, src/features/auth/providers.tsx, src/features/layout/LeftNavBar.tsx, src/features/login/LogIn.tsx, src/features/login/LoggedOut.tsx, src/features/login/Policies.tsx, src/features/signup/AccountInformation.tsx, src/features/signup/ProviderSelect.tsx, src/theme.tsx
=> Account Page Migration

config.json
See https://kbase.slack.com/archives/C4E7KUGTD/p1744055858948379?thread_ts=1744049701.967629&cid=C4E7KUGTD
=> Add session cookie to narrative_dev
